version: "3.3"

services:
  db:
    container_name: "db"
    image: postgres
    volumes:
      - qiradb:/var/lib/postgresql/data

  web:
    container_name: "web"
    image: bak3dchips/qira-django:latest
    volumes:
      - qiradata:/qira-django
    ports:
      - "80:8000"
    env_file:
      - qira.env
    depends_on:
      - db

  rds:
    container_name: "remote-ds"
    image: bak3dchips/remote-ds
  
  watchtower:
    image: containrrr/watchtower:latest
    container_name: "watchtower"
    command: ["watchtower","web","db",
    "-e", "WATCHTOWER_NOTIFICATIONS=email",
    "-e", "WATCHTOWER_NOTIFICATION_EMAIL_FROM=${FROM}",
    "-e", "WATCHTOWER_NOTIFICATION_EMAIL_TO=${TO}",
    "-e", "WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SERVER}",
    "-e", "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${FROM}",
    "-e", "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${PASS}",
    "-e", "WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2",
    "-e", "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587"   
    ]
    environment:
      - FROM
      - TO
      - SERVER
      - PASS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: unless-stopped

volumes:
  qiradb:
    external: true
  qiradata:
    external: true