version: "3.3"

services:
  db:
    #container_name: "db"
    image: postgres
    volumes:
      - qiradb:/var/lib/postgresql/data

  web:
    #container_name: "web"
    image: bak3dchips/qira-django:0.0.30-amd64
    ports:
      - "80:8000"
    env_file:
      - qira.env
    depends_on:
      - db
    volumes:
      - .:/qira-django

  rds:
    #container_name: "remote-ds"
    image: bak3dchips/remote-ds:latest
    ports:
      - "1150:1150"
      - "1110:1110"
  
  watchtower:
    image: containrrr/watchtower
    #container_name: "watchtower"
    command: "--notifications slack --notification-slack-hook-url 'rephook'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: unless-stopped

volumes:
  qiradb:
    external: true
