version: "3.3"

services:
  db:
    container_name: "db"
    image: postgres
    volumes:
      - qiradb:/var/lib/postgresql/data

  web:
    container_name: "web"
    image: bak3dchips/qira-django
    volumes:
      - qiradata:/qira-django
    ports:
      - "80:8000"
    env_file:
      - qira.env
    depends_on:
      - db
  
  watchtower:
    image: containrrr/watchtower:latest
    container_name: "watchtower"
    command: ["watchtower","-v","/var/run/docker.sock:/var/run/docker.sock" "web","db"]
    restart: unless-stopped

volumes:
  qiradb:
    external: true
  qiradata:
    external: true