version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - qiradb:/var/lib/postgresql/data

  web:
    image: bak3dchips/qira-django:latest
    volumes:
      - qiradata:/qira-django
    ports:
      - "80:8000"
    env_file:
      - qira.env
    depends_on:
      - db

volumes:
  qiradb:
    external: true
  qiradata:
    external: true