version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - qiradb:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"
    env_file:
      - qira.env
    depends_on:
      - db

volumes:
  qiradb:
    external: true