version: "3.3"

services:
  db:
    #container_name: "db"
    image: postgres
    volumes:
      - qiradb:/var/lib/postgresql/data

  web:
    #container_name: "web"
    image: bak3dchips/qira-django:latest
    ports:
      - "80:8000"
    env_file:
      - qira.env
    depends_on:
      - db

  rds:
    #container_name: "remote-ds"
    image: bak3dchips/remote-ds:latest
  
  watchtower:
    image: v2tec/watchtower:armhf-latest
    #container_name: "watchtower"
    command: "--notifications slack --notification-slack-hook-url 'https://hooks.slack.com/services/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'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: unless-stopped

volumes:
  qiradb:
    external: true