# Generated by Django 3.0 on 2020-01-22 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robot_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeprojects',
            name='id',
        ),
        migrations.AddField(
            model_name='codeprojects',
            name='document',
            field=models.TextField(default=b'\x93\xdb4\xb6\x1e\xff7\x94\xd30\x1e\x86,]\xe1\xa0\x1c\xd0\x07[*\xe8i\x18\x00\x9cb\xe37[IL', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(max_length=25)),
                ('teacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='codeprojects',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot_control.Member'),
        ),
    ]
