# Generated by Django 3.0 on 2020-01-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0003_auto_20200122_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeprojects',
            name='document',
            field=models.TextField(default=b'\x9bS\n\xe5\x80\xf3\x14\xdd\xe2Iu\xb1\x9d\x87\xe5\xf1M\\GaE\x0e\xf8@ \xad+j\xa0y\xa2l', primary_key=True, serialize=False),
        ),
    ]
